export { default as Navbar } from "./global/Navbar";
export { default as Footer } from "./global/Footer";
export { default as Hero } from "./Hero";
export { default as AboutUs } from "./AboutUs";
export { default as Service } from "./Service";
export { default as Success } from "./Success";
export { default as Team } from "./Team";
export { default as Testimonial } from "./Testimonial";
export { default as Contact } from "./Contact";
